### ISSUE TITLE
Buttons did not draw correctly....

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap-theme#11]
how are the buttons for this not drawing correctly on my local install?
![gravstrap button not drawing](https://cloud.githubusercontent.com/assets/830306/13719834/ae59386c-e82e-11e5-8e8d-6cb9ea292c21.gif)

edit: I downloaded a separate gravstrap skeleton and all is well in that folder.  not sure what happened with the one installed via admin panel.

so without an admin panel, do I need to use markdown pro to edit pages?  Can I add admin panel to skeleton?

Also, you notice that the large words "Gravstrap" are being overlapped by the page header (when you scroll down a little.  how do you force the Gravstrap text and other text to not overlap?

If there was a chat room or forum, I can post there also.

**Comment by giansi** [comment]
Buttons are not rendered because you must enable markdown extra. http://diblas.net/themes/gravstrap-theme-helps-to-start-a-new-grav-cms-site-with-bootstrap-support/how-to-install-gravstrap-theme#setup.

Yes, you can add admin panel to skeleton.

**Comment by 4evermaat** [comment]
Great.  But it would be nice if you explain to the user why certain changes are made/done so they can follow along.
