### ISSUE TITLE
Continue Reading translate

### ISSUE THREAD

**Issue by ocean123** [giansi/gravstrap-theme#14]
Hi,

how can I make a translation for "Continue Reading"
and what if there is a up-date of the theme.
can you add the translation option for this part.

beste regards

**Comment by giansi** [comment]
I will do it ASAP

**Comment by ocean123** [comment]
:+1:

**Comment by giansi** [comment]
Solved with this release https://github.com/giansi/grav-plugin-blog/releases/tag/v1.2.0
