### ISSUE TITLE
custom.css empty after update

### ISSUE THREAD

**Issue by ocean123** [giansi/gravstrap-theme#16]
Hi,

my custom.css was empty after updating to the newest version.
off course I had a update.

best regards

**Comment by giansi** [comment]
Sorry for that. That implementation can't work. I will fix it ASAP

**Comment by giansi** [comment]
Hi, I've removed the custom.css file but left the declaration as in the Antimatter theme and this should fix. Anyway, you should add the custom.css in a derided theme not in Gravstrap Theme. You've got this change in 1.0.5 release
