### ISSUE TITLE
New shortcode core update breaks menus

### ISSUE THREAD

**Issue by 2braincells2go** [giansi/gravstrap-theme#22]
Firstly, great theme and have learned much from it, thank you.

I updated to the "shortcode core" plugin that was released yesterday. Doing so completely removes the header / footer menus in Gravstrap. Had to restore old version is shrotcode core plugin to get site working.

Opened issue at Grav but was closed so not sure if shortcode core plugin or Gravstrap. Thought you may like to know and see if you can reproduce.

Thanks!

Woody

**Comment by giansi** [comment]
Thank you! Glad you like Gravstrap theme. :-) Upgrading Gravstrap plugin to 1.1.3 should solve the issue. Please close the issue if that fixes, otherwise let me know.

**Comment by 2braincells2go** [comment]
Yes that fixed, thank you much!
