### ISSUE TITLE
Portfolio Images Disappeared

### ISSUE THREAD

**Issue by 2braincells2go** [giansi/gravstrap-theme#24]
Greetings! We updated our site to the latest release day or two ago.

Before that the portfolio was working fine and now the images have completed disappeared.

Running the admin plugin so all we did was auto update, no manual intervention.

https://qiksoft.com/

Any ideas on fix?

Thank you for your time.

**Comment by giansi** [comment]
Hi,
this should help you to fix: http://diblas.net/plugins/use-bootstrap-components-as-shortcodes-in-grav-cms/how-to-handle-components-images.

Anyway, I've tweeted about this change here, https://twitter.com/gravstrap/status/755442474919878657.

At last, this http://diblas.net/blog/how-to-deploy-a-website-using-rocketeer could help you to implement a better deployment strategy. ;-)

**Comment by 2braincells2go** [comment]
Ok, so you are saying to no longer rely on Gravstrap to work as coded?

```
[g-portfolio name=portfolio attributes="class:portfolio module"]

## Some of Our Software
These are only a few `samples` of our work

___

[g-thumbnail]
[g-thumbnail-item image="minimen.jpg"][/g-thumbnail-item]
[g-thumbnail-item image="cleansqueeze.jpg"][/g-thumbnail-item]
[g-thumbnail-item image="footercash.jpg"][/g-thumbnail-item]
[g-thumbnail-item image="qikmobi.jpg"][/g-thumbnail-item]
[g-thumbnail-item image="qikcart.jpg"][/g-thumbnail-item]
[g-thumbnail-item image="secondchance.jpg"][/g-thumbnail-item]
[/g-thumbnail]

[/g-portfolio]
```

**Comment by giansi** [comment]
You must create a page, so a folder under user/pages, and put your images
inside that folder. The sc code remains the same

Il 24 Lug 2016 12:34, "Woody" notifications@github.com ha scritto:

**Comment by 2braincells2go** [comment]
I get it now. Couple cups of coffee and my mind cleared:)

Thanks much.
