### ISSUE TITLE
issues with google map api

### ISSUE THREAD

**Issue by delblues** [giansi/gravstrap-theme#27]
H @giansi 

It seems that there is an issue with the use of shortcode for google map api, as long as I'm trying to follow your instructions here `http://diblas.net/plugins/gravstrap/google-map-component` , it is not working. 
The JS keeps asking for the api and does not run the map in the page: `http://audleste.com.br/grav-admin/br/gravstrap-theme-simple-page-example`

congrats for the template anyway
tks

**Comment by giansi** [comment]
Hi,
you require an api key to get it run, but there was a typo in the doc: the correct parameter name is **api-key** not **api_key**. I've updated the documentation.

Glad you like the theme. :-)

**Comment by delblues** [comment]
@giansi  nice to hear, tks for the repply.
