### ISSUE TITLE
Navbar Covers Heading

### ISSUE THREAD

**Issue by axel-rank** [giansi/gravstrap-theme#7]
Hi, tried your wonderful Gravstrap Theme. Will probably use it until final release is out.
Only one thing: In 'Home Single' One Page Demo all the Section Headings are covered by navbar. Guess it's the wrong css padding.

![screenshot](https://cloud.githubusercontent.com/assets/12480617/13388154/f3c39124-debd-11e5-86e3-dec523900f64.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/12480617/13388168/03f758e6-debe-11e5-9a7e-8129bcb0d628.jpg)

Seems to be a Firefox Issue. Chromium works!

**Comment by giansi** [comment]
HI could you try with the latest versions I pushed to master branches and let me know if that is fine for you? It's a little tricky to setup. Get the last version from here, https://github.com/giansi/gravstrap-theme-skeleton/releases/download/v1.0.0-rc.5/gravstrap-skeleton.tar.gz, then remove the plugins/gravstrap theme and get the latest from master branch here, https://github.com/giansi/gravstrap. Do the same with gravstrap-theme, https://github.com/giansi/gravstrap-theme, then remove the pages folder and grab them  again from here https://github.com/giansi/gravstrap-theme-skeleton.

**Comment by giansi** [comment]
Fixed with 1.0.0 release.
