### ISSUE TITLE
Cannot install gravstrap-theme in local wamp 3.0 grav admin panel

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap-theme#8]
`Error while trying to download 'https://github.com/getgrav/grav-plugin-shortcode-core/zipball/2.0.2'`

That is the error I receive on screen when I try to install the gravstrap theme.  I installed a different theme and even a plugin to make sure admin panel could install properly.  They installed just fine.  So what did I do wrong?

**Comment by giansi** [comment]
Hi,
just tried starting from a fresh grav-admin version and it works. Gravstrap theme requires several plugins to work. Maybe you had a connection problem or your php must be hacked. Try again with your configuration and if it still does not work, try to increase the max_execution_time setting and set the memory_limit to -1. If you still have problems, try to go with the gpm http://diblas.net/themes/gravstrap-theme-helps-to-start-a-new-grav-cms-site-with-bootstrap-support/how-to-install-gravstrap-theme#manual-installation or consider to start from the gravstrap-skeleton https://github.com/giansi/gravstrap-theme-skeleton/releases/download/v1.0.3/gravstrap-skeleton.zip.

When you are done, do not forget to follow these steps to complete the configuration: http://diblas.net/themes/gravstrap-theme-helps-to-start-a-new-grav-cms-site-with-bootstrap-support/how-to-install-gravstrap-theme#setup
