### ISSUE TITLE
120 second time-out

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap-theme#9]
i'm using php 5.6.15, apache 2.4.17, and mySql 5.7.9. (wamp 3.0.4; win7 64 bit)

I attempted to download again using the admin panel within grav.  I got a weird timeout error that is best explained with a screenshot.
![load gravstrap theme in grav admin](https://cloud.githubusercontent.com/assets/830306/13700092/5bb07b52-e7b1-11e5-9f74-55a1c785353b.gif)

now after i refreshed the admin panel, I noticed that the theme seemed to download in its entirety.  But it was version 1.0.2

**Comment by giansi** [comment]
As I told you here https://github.com/giansi/gravstrap-theme/issues/8 you have to increase the max_execution_time in your pho.ini file. I guess 300 could be a good value. I'm not confortable with windows, so I can't help you with this configuration.
